---
title: "string_practice"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(palmerpenguins)
library(lubridate)
library(datapasta)
library(here)

```

```{r}
alarm_report <- tibble::tribble(
         ~date,           ~building,                                               ~alarm_message,
  "2020-03-14", "Engineering-North", "10:02am -- HVAC system down, facilities management alerted",
  "2020-03-15",         "Bren Hall",                    "8:24am -- Elevator North out of service",
  "2020-04-10", "Engineering-South",     "12:41am -- Fire alarm, UCSB fire responded and cleared",
  "2020-04-18",        "Engr-North",     "9:58pm -- Campus point emergency siren, UCPD responded"
  )

```

```{r}
alarm_report_update <- alarm_report %>%
  mutate(building=str_replace(building, pattern = "Engr", replacement = "Engineering")) %>%
  separate(col = building, sep = "-", into = c("building", "wing")) %>%
  filter(str_detect(alarm_message, "responded")) %>%
  separate(col=alarm_message, sep = "--", into = c("time", "alarm_message")) %>%
  mutate(data=lubridate::date(date))
```
 





















